version: "3.9"

services:
  bolsa_scraper:
    image: scraper-bolsa
    container_name: bolsa_scraper
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./log.txt:/app/log.txt
